INSERT INTO  brand (brand_id, brand)
VALUES
(1, "ROLEX"),
(2, "JAEGER-LECOULTRE"),
(3, "OMEGA"),
(4, "PATEK PHILIPPE"),
(5, "VACHERON CONSTANTIN"),
(6, "AUDEMARS PIGUET"),
(7, "BREITLING"),
(8, "CARTIER"),
(9, "IWC"),
(10, "TAG HEUER");


INSERT INTO watch (brand_id, watch, dial_type, watch_desc, price, imgURL)
VALUES 
( 1, "PAUL NEWMAN'S ROLEX DAYTONA", 
'ANALOG', 
"THIS WATCH IS PAUL NEWMAN'S COLLAB WHICH ONLY HAS ONLY A CERTAIN AMOUNT OF REFERNCE NUMBERS IT CAN BE ASSOCIATED WITH. THIS WATCH IS FEATURES AN 'EXOTIC DIAL' WITH CONTRASTING SUB-DIALS AND ART DECO DETAILING.", 
17800000, ""),

(2, "HYBRIS MECHANICA A GRANDE SONNERIE", "ANALOG", 
"THE TIMEPIECE FEATURES AN INTRICATE, 1,300-PART FLYING TOURBILLON AND PARTIALLY SKELETONIZED CASE. ONLY 30 OF THESE WATCHES WERE MADE.", 
2500000, ""),

(3, "THE SPEEDMASTER", "ANALOG", "THIS WATCH FEATURES A BROWN LEATHER BAND, A TROPICAL BROWN DIAL, AND A 38 MM STAINLESS STEEL CASE.", 3400000, ""),

(4, "PATEK PHILIPPE GRANDMASTER CHIME", "ANALOG", "THIS PATEK'S CASE FEATURES A BLEND OF POLISHED AND BRUSHED FINISHES, AND THE WATCH'S INTRICATE DETAILS ARE VISIBLE THROUGH THE SAPPHIRE CRYSTAL CASE BACK", 31000000, ""),

(5, "VACHERON CONSTANTIN KALISTA", "ANALOG", "THIS WATCH HAS 118 EMERALD-CUT DIAMONDS, THE INTRICATE DESIGN TOOK 6,000 MAN-HOURS TO COMPLETE AND AN ADDITIONAL 20 MONTHS FOR THE LABORIOUS ENCRUSTATION OF THE JEWELS.", 11000000, ""),

(6, "AUDEMARS PIGUET ROYAL OAK TOURBILLION CHRONOGRAPH", "ANALOG", "THIS TIMEPIECE HAS 18-CARAT YELLOW GOLD CASE FRAMED WITH 276 BRILLIANT CUT DIAMONDS WEIGHING 3.75 CARATS!", 721000, ""),

(7, "BREITLING BENTLEY FLYING B", "ANALOG", "THIS WATCH EPITOMIZES THE PINNACLE OF LUXURY AND CRAFTSMANSHIP WITHIN THE BENTLEY FLYING B COLLECTION OF BREITLING", 255000, ""),

(8, "CARTIER PHOENIX DECOR SECRET WATCH", "ANALOG", "TINY EMERALDS SERVE AS THE EYES AND THE DIAL IS HIDDEN AMONG THE FEATHERS ON THE BACK OF THE PHEONIX. THIS WATCH IS MADE WITH OVER 3000 DIAMONDS AND OTHER COLORFUL GEMSTONES.", 3800000, ""),

(9, "IWC SIDERALE SCAFUSIA", "ANALOG", "THIS IS ONE OF THE MOST COMPLEX WATCH MANUFACTURED BY THE IWC. THE OVERSIZED TOURBILLION HAS AN ASTRONOMICAL DISPLAY AND GIVE RUNNING SECONDS AND KEEPS THE CORRECT TIME FOR OVER 48 HOURS.", 750000, ""),

(10, "TAG HEUER CARRERA PLASMA TOURBILLION" , "ANALOG", "THIS WATCH HAS 2.5-CARET LAB-GROWN DIAMONDS SHAPED LIKE A CROWN. THE WATCH IS FITTED WITH A SPARKLING DIAL WITH FINELY GROUND DIAMOND 'POWDER' THAT IS BLASTED ONTO THE SURFACE WHAT TAG HEUER CALLS 'POLYCRYSTALLINE DIAMOND DIAL'", 376000, "");

INSERT INTO user (fName, lName, email, username, password)
VALUES
("DHON",
"SEARGENT",
"dhon@mscodingacademies.org",
"DhonCodingProdigy",
"Fatmuscle23@"
);

UPDATE watch
SET imgURL = "daytonarolex.jpg"
WHERE watch_id = 1;

UPDATE watch
SET imgURL = "hybris.jpg"
WHERE watch_id = 2;

UPDATE watch
SET imgURL = "omega.jpg"
WHERE watch_id = 3;

UPDATE watch
SET imgURL = "patek.jpg"
WHERE watch_id = 4;

UPDATE watch
SET imgURL = "kallista.jpg"
WHERE watch_id = 5;

UPDATE watch
SET imgURL = "audemars.jpg"
WHERE watch_id = 6;

UPDATE watch
SET imgURL = "bentley.jpg"
WHERE watch_id = 7;

UPDATE watch
SET imgURL = "cartier.jpg"
WHERE watch_id = 8;

UPDATE watch
SET imgURL = "iwc.jpg"
WHERE watch_id = 9;

UPDATE watch
SET imgURL = "tag.jpg"
WHERE watch_id = 10;

